[tool.isort]
profile = "black"
known_first_party = ["."]
skip = []

[tool.black]
line-length = 88
exclude = '''/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | docker
  | config
  | temp
  | src/desc/repository/sqlalchemy/migration/alembic
)/'''